# fly.toml app configuration file generated for style on 2025-10-18T14:46:37-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'style'
primary_region = 'ord'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'style.fly.dev'
  PORT = '8080'
  # Optimize BEAM VM for low memory
  ERL_MAX_PORTS = '4096'
  POOL_SIZE = '2'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 50

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
